- teslaField: Location
  teslaType: LocationValue
  vssSignal: Vehicle.CurrentLocation.Latitude

- teslaField: Location
  teslaType: LocationValue
  vssSignal: Vehicle.CurrentLocation.Longitude

- teslaField: DetailedChargeState
  teslaType: DetailedChargeStateValue
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.IsCharging

- teslaField: ACChargingPower
  teslaType: string
  teslaUnit: kW
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.CurrentPower.AC
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT
  # split VSS signal into AC and DC

- teslaField: DCChargingPower
  teslaType: string
  teslaUnit: kW
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.CurrentPower.DC
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT
  # split VSS signal into AC and DC

- teslaField: ACChargingEnergyIn
  teslaType: string
  teslaUnit: kWh
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.AddedEnergy.AC
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT
 # split VSS signal into AC and DC

- teslaField: DCChargingEnergyIn
  teslaType: string
  teslaUnit: kWh
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.AddedEnergy.DC
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT
 # split VSS signal into AC and DC

- teslaField: Soc
  teslaType: string
  teslaUnit: percent
  vssSignal: Vehicle.Powertrain.TractionBattery.StateOfCharge.Current
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: TpmsPressureFl
  teslaType: string
  teslaUnit: bar
  vssSignal: Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.Pressure
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: TpmsPressureFr
  teslaType: string
  teslaUnit: bar
  vssSignal: Vehicle.Chassis.Axle.Row1.Wheel.Right.Tire.Pressure
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: TpmsPressureRl
  teslaType: string
  teslaUnit: bar
  vssSignal: Vehicle.Chassis.Axle.Row2.Wheel.Left.Tire.Pressure
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: TpmsPressureRr
  teslaType: string
  teslaUnit: bar
  vssSignal: Vehicle.Chassis.Axle.Row2.Wheel.Right.Tire.Pressure
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: OutsideTemp
  teslaType: string
  teslaUnit: celsius
  vssSignal: Vehicle.Exterior.AirTemperature
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: EstBatteryRange
  teslaType: string
  teslaUnit: mi
  vssSignal: Vehicle.Powertrain.Range
  automations:
  - PARSE_FLOAT
  # Can't convert units automatically because the VSS spec has meters, but we've always output kilometers.

- teslaField: ChargeLimitSoc
  teslaType: string
  teslaUnit: percent
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.ChargeLimit
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: VehicleSpeed
  teslaType: string
  teslaUnit: mph
  vssSignal: Vehicle.Speed
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: BrickVoltageMax
  teslaType: string
  teslaUnit: V
  vssSignal: Vehicle.Powertrain.TractionBattery.CellVoltage.Max
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: BrickVoltageMin
  teslaType: string
  teslaUnit: V
  vssSignal: Vehicle.Powertrain.TractionBattery.CellVoltage.Min
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: CarType
  teslaType: string
  vssSignal: Vehicle.VehicleIdentification.Model 

- teslaField: ChargeAmps
  teslaType: string
  teslaUnit: A
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.AllPhases 
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT
  #Jeremy invented signal because current is not given in phases. Note that this signal appears to only track amps for AC charging, not supercharging (the max observed is 48 Amps, but a supercharge should be over 400 amps)


- teslaField: CruiseFollowDistance
  teslaType: string
  vssSignal: Vehicle.ADAS.CruiseControl.CruiseFollowTime 
  automations:
  - PARSE_FLOAT
  # Tesla cruise follow distance seems to be directly proportional to time, but is not seconds

- teslaField: CruiseSetSpeed
  teslaType: string
  teslaUnit: km/h
  vssSignal: Vehicle.ADAS.CruiseControl.SpeedSet 
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT
# Jeremy is 99% sure that the Tesla signal is in kph, where speed is in mph, which is unpleasant if true

- teslaField: CurrentLimitMph
  teslaType: string
  teslaUnit: mph
  vssSignal: Vehicle.VehicleIdentification.Model.MaxSpeedAllowed 
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT
# Jeremy invented this signal because "speed limit mode" does not appear to be a VSS signal

- teslaField: EmergencyLaneDepartureAvoidance
  teslaType: string
  vssSignal: Vehicle.ADAS.LaneDepartureDetection.IsEnabled
  automations:
  - PARSE_BOOLEAN

- teslaField: ForwardCollisionWarning
  teslaType: string
  vssSignal: Vehicle.ADAS.ObstacleDetection.Forward.Setting
# This is the sensitivity setting for the forward collision warning
# Split out Vehicle.ADAS.ObstacleDetection into forward and blind spot

- teslaField: GuestModeEnabled
  teslaType: string
  vssSignal: Vehicle.GuestModeEnabled 
  automations:
  - PARSE_BOOLEAN
  # Jeremy invented this signal because guest mode is pretty Tesla specific

- teslaField: IdealBatteryRange
  teslaType: string
  teslaUnit: mi
  vssSignal: Vehicle.Powertrain.IdealRange
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT
  # Jeremy invented this signal

- teslaField: Odometer
  teslaType: string
  teslaUnit: mi
  vssSignal: Vehicle.Powertrain.Transmission.TravelledDistance
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT
# Jeremy used powertrain odometer instead of vehicle odometer because DIMO has been using powertrain odometer

- teslaField: EnergyRemaining
  teslaType: string
  teslaUnit: kWh
  vssSignal: Vehicle.Powertrain.TractionBattery.StateOfCharge.CurrentEnergy
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: LaneDepartureAvoidance
  teslaType: string
  vssSignal: Vehicle.ADAS.LaneDepartureDetection.Level
# Jeremy invented this signal

# Parse the Tesla Locked signal into all four door IsLocked VSS signals
- teslaField: Locked
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row1.DriverSide.IsLocked
  automations:
  - PARSE_BOOLEAN

- teslaField: Locked
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row2.DriverSide.IsLocked
  automations:
  - PARSE_BOOLEAN

- teslaField: Locked
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row1.PassengerSide.IsLocked
  automations:
  - PARSE_BOOLEAN

- teslaField: Locked
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row2.PassengerSide.IsLocked
  automations:
  - PARSE_BOOLEAN
# </Four door signals>

# Remove these because we have the timestamp associated with each pressure reading
# - teslaField: TpmsLastSeenPressureTimeFl
#   teslaType: string
#   teslaUnit: timestamp
#   vssSignal: Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.PressureTimestamp
#   automations:
#   - PARSE_TIMESTAMP
#   - CONVERT_UNIT

# - teslaField: TpmsLastSeenPressureTimeFr
#   teslaType: string
#   teslaUnit: timestamp
#   vssSignal: Vehicle.Chassis.Axle.Row1.Wheel.Right.Tire.PressureTimestamp
#   automations:
#   - PARSE_TIMESTAMP
#   - CONVERT_UNIT

# - teslaField: TpmsLastSeenPressureTimeRl
#   teslaType: string
#   teslaUnit: timestamp
#   vssSignal: Vehicle.Chassis.Axle.Row2.Wheel.Left.Tire.PressureTimestamp
#   automations:
#   - PARSE_TIMESTAMP
#   - CONVERT_UNIT

# - teslaField: TpmsLastSeenPressureTimeRr
#   teslaType: string
#   teslaUnit: timestamp
#   vssSignal: Vehicle.Chassis.Axle.Row2.Wheel.Right.Tire.PressureTimestamp
#   automations:
#   - PARSE_TIMESTAMP
#   - CONVERT_UNIT

- teslaField: Trim
  teslaType: string
  vssSignal: Vehicle.VehicleIdentification.Trim
  # Jeremy invented this signal

- teslaField: VehicleName
  teslaType: string
  vssSignal: Vehicle.VehicleIdentification.VehicleName
  # Jeremy invented this signal

- teslaField: Version
  teslaType: string
  vssSignal: Vehicle.VehicleIdentification.VehicleSoftwareVersion
  # Jeremy invented this signal

- teslaField: FastChargerPresent
  teslaType: string
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.IsFastChargingCableConnected
  automations:
  - PARSE_BOOL
  # Jeremy invented this signal (based on `Charging.IsChargingCableConnected`)

- teslaField: DoorState
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row1.DriverSide.IsOpen

- teslaField: DoorState
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row2.DriverSide.IsOpen

- teslaField: DoorState
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row1.PassengerSide.IsOpen

- teslaField: DoorState
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row2.PassengerSide.IsOpen

# Is item open or closed? True = Fully or partially open. False = Fully closed.	 (Map Tesla fields to True/False)
- teslaField: FdWindow
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row1.DriverSide.Window.IsOpen

- teslaField: FpWindow
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row1.PassengerSide.Window.IsOpen

- teslaField: RdWindow
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row2.DriverSide.Window.IsOpen

- teslaField: RpWindow
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row2.PassengerSide.Window.IsOpen

- teslaField: BlindSpotCollisionWarningChime
  teslaType: string
  vssSignal: Vehicle.ADAS.ObstacleDetection.BlindSpot.IsEnabled
  automations:
  - PARSE_BOOL
# Split out Vehicle.ADAS.ObstacleDetection into forward and blind spot

- teslaField: SpeedLimitWarning
  teslaType: string
  vssSignal: Vehicle.ADAS.SpeedLimitWarning
  # Jeremy invented this signal

- teslaField: AutomaticEmergencyBrakingOff
  teslaType: string
  vssSignal: Vehicle.ADAS.EBA.IsEnabled
  automations:
  - PARSE_BOOL

- teslaField: ChargerVoltage
  teslaType: doubleValue
  teslaUnit: V
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.ChargeVoltage.ChargeVoltage
  automations: 
  - CONVERT_UNIT
  - PARSE_FLOAT

- teslaField: ChargingCableType
  teslaType: ChargingCableTypeValue
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.ChargePortType

- teslaField: SoftwareUpdateVersion
  teslaType: string
  vssSignal: Vehicle.VehicleIdentification.VehicleSoftwareUpdateVersion
# Jeremy invtented this signal
