- teslaField: Location
  teslaType: LocationValue
  vssSignal: Vehicle.CurrentLocation.Latitude

- teslaField: Location
  teslaType: LocationValue
  vssSignal: Vehicle.CurrentLocation.Longitude

# TODO(elffjs): Express more of the subtlety of the source enum, which has 7 possibilities.
- teslaField: DetailedChargeState
  teslaType: DetailedChargeStateValue
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.IsCharging

- teslaField: ACChargingPower
  teslaType: string
  teslaUnit: kW
  vssSignal: Vehicle.Powertrain.TractionBattery.CurrentPower # Happily, in VSS this is positive for charging.
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: DCChargingPower
  teslaType: string
  teslaUnit: kW
  vssSignal: Vehicle.Powertrain.TractionBattery.CurrentPower
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

# # TODO(elffjs): Bring this back?
# - teslaField: ACChargingEnergyIn
#   teslaType: string
#   teslaUnit: kWh
#   vssSignal: Vehicle.Powertrain.TractionBattery.Charging.AddedEnergy
#   automations:
#   - PARSE_FLOAT
#   - CONVERT_UNIT

# Despite the name, this is the amount of energy added during any charging session, AC or DC.
# For AC charging, the difference is that this number is measured at the battery and
# ACChargingEnergyIn is measured at the charger.
- teslaField: DCChargingEnergyIn
  teslaType: string
  teslaUnit: kWh
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.AddedEnergy
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: EnergyRemaining
  teslaType: string
  teslaUnit: kWh
  vssSignal: Vehicle.Powertrain.TractionBattery.StateOfCharge.CurrentEnergy
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: Soc
  teslaType: string
  teslaUnit: percent
  vssSignal: Vehicle.Powertrain.TractionBattery.StateOfCharge.Current
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: TpmsPressureFl
  teslaType: string
  teslaUnit: atm
  vssSignal: Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.Pressure
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: TpmsPressureFr
  teslaType: string
  teslaUnit: atm
  vssSignal: Vehicle.Chassis.Axle.Row1.Wheel.Right.Tire.Pressure
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: TpmsPressureRl
  teslaType: string
  teslaUnit: atm
  vssSignal: Vehicle.Chassis.Axle.Row2.Wheel.Left.Tire.Pressure
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: TpmsPressureRr
  teslaType: string
  teslaUnit: atm
  vssSignal: Vehicle.Chassis.Axle.Row2.Wheel.Right.Tire.Pressure
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: OutsideTemp
  teslaType: string
  teslaUnit: celsius
  vssSignal: Vehicle.Exterior.AirTemperature
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

# Note, too, the existence of IdealBatteryRange and RatedRange.
- teslaField: EstBatteryRange
  teslaType: string
  teslaUnit: mi
  vssSignal: Vehicle.Powertrain.Range
  automations:
  - PARSE_FLOAT
  # Can't convert units automatically because the VSS spec has meters, but we've always output kilometers.

- teslaField: ChargeLimitSoc
  teslaType: string
  teslaUnit: percent
  vssSignal: Vehicle.Powertrain.TractionBattery.Charging.ChargeLimit
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: VehicleSpeed
  teslaType: string
  teslaUnit: mph
  vssSignal: Vehicle.Speed
  automations:
  - PARSE_FLOAT
  - CONVERT_UNIT

- teslaField: DoorState
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row1.DriverSide.IsOpen

- teslaField: DoorState
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row1.PassengerSide.IsOpen

- teslaField: DoorState
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row2.DriverSide.IsOpen

- teslaField: DoorState
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row2.PassengerSide.IsOpen

- teslaField: FdWindow
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row1.DriverSide.Window.IsOpen

- teslaField: FpWindow
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row1.PassengerSide.Window.IsOpen

- teslaField: RdWindow
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row2.DriverSide.Window.IsOpen

- teslaField: RpWindow
  teslaType: string
  vssSignal: Vehicle.Cabin.Door.Row2.PassengerSide.Window.IsOpen
